spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=tradedb;encrypt=true;trustServerCertificate=true;
    username: sa
    password: a0972780085Z
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
